### ISSUE TITLE
Kotlin - Not able to load pdf using URI 

### ISSUE THREAD

**Issue by bhaskarraj** [barteksc/AndroidPdfViewer#1016]
I am using this library to load pdf from URL, but it's giving me some problem.

` java.io.FileNotFoundException: No content provider: https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1684)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1514)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1349)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1297)
        at com.github.barteksc.pdfviewer.source.UriSource.createDocument(UriSource.java:37)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)`
        
  My source code is : 
  
  `
  
  val url ="https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf"

  pdfView.fromUri(Uri.parse(url))
            .pages(0, 2, 1, 3, 3, 3) // all pages are displayed by default
            .enableSwipe(true) // allows to block changing pages using swipe
            .swipeHorizontal(false)
            .enableDoubletap(true)
            .defaultPage(0)
            .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
            .password(null)
            .scrollHandle(null)
            .enableAntialiasing(true) // improve rendering a little bit on low-res screens
            // spacing between pages in dp. To define spacing color, set view background
            .spacing(0)
            .load();`

**Comment by Pannarrow** [comment]
download pdf
