### ISSUE TITLE
Unable to load PDF from URL

### ISSUE THREAD

**Issue by supportreq** [barteksc/AndroidPdfViewer#123]
I am trying to load PDF fromUri, using a http request, it is returning:
`PDFView: load pdf error
                                                        java.io.FileNotFoundException: No content provider: http://kmmc.in/wp-content/uploads/2014/01/lesson2.pdf
                                                            at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1093)
                                                            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944)
                                                            at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:797)
                                                            at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:751)
                                                            at com.github.barteksc.pdfviewer.DecodingAsyncTask.getSeekableFileDescriptor(DecodingAsyncTask.java:82)
                                                            at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:61)
                                                            at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:30)
                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                            at java.lang.Thread.run(Thread.java:818)
`

**Comment by barteksc** [comment]
Remote files are not supported

**Comment by supportreq** [comment]
@barteksc does the new version support fromuri?

please advice..

**Comment by barteksc** [comment]
@supportreq `fromUri()` exists for a long time, but it doesn't support remote files and probably never will. Downloading files is long running process which must be aware of Activity lifecycle, must support some configuration, data cleanup and caching, so creating such module will probably end up as new library.
