### ISSUE TITLE
Occasional NullPointerException when showing a PDF

### ISSUE THREAD

**Issue by niekvse** [barteksc/AndroidPdfViewer#14]
Occasionally, I get a NullPointerException when trying to show a PDF. I haven't really found a pattern yet - it doesn't seem related to the PDF, or if it is, the same PDF still works fine most of the time.

Version 1.1.1.

I suppose it's caused by an (internal) call to public void removeAllTasks(), which is not synchronized.

``` java
06-24 15:52:03.663 17306-17422/com.xxxx.android.beta D/jniPdfium: Draw Ver: 1536
06-24 15:52:03.663 17306-17422/com.xxxx.android.beta D/jniPdfium: Start X: 0
06-24 15:52:03.663 17306-17422/com.xxxx.android.beta D/jniPdfium: Start Y: -256
06-24 15:52:03.663 17306-17422/com.xxxx.android.beta D/jniPdfium: Canvas Hor: 256
06-24 15:52:03.663 17306-17422/com.xxxx.android.beta D/jniPdfium: Canvas Ver: 256
06-24 15:52:03.663 17306-17422/com.xxxx.android.beta D/jniPdfium: Draw Hor: 1280
06-24 15:52:03.663 17306-17422/com.xxxx.android.beta D/jniPdfium: Draw Ver: 1536
06-24 15:52:03.673 17306-17422/com.xxxx.android.beta E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                        Process: com.xxxx.android.beta, PID: 17306
                                                                        java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.NullPointerException: Attempt to read from field 'float com.github.barteksc.pdfviewer.RenderingAsyncTask$RenderingTask.width' on a null object reference
                                                                            at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:103)
                                                                            at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:67)
                                                                            at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:31)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                            at java.lang.Thread.run(Thread.java:818) 
```

**Comment by isanwenyu** [comment]
I have the same problem. 
Version 1.2.0

**Comment by barteksc** [comment]
Fixed
