### ISSUE TITLE
InputStreamSource OOM for 130 MB pdf file

### ISSUE THREAD

**Issue by lewkka** [barteksc/AndroidPdfViewer#147]
11-23 05:15:55.982 5385-5485/com.github.barteksc.sample E/art: Throwing OutOfMemoryError "Failed to allocate a 67100684 byte allocation with 16777216 free bytes and 62MB until OOM"
11-23 05:15:55.983 5385-5385/com.github.barteksc.sample E/PDFView: load pdf error
                                                                   java.lang.OutOfMemoryError: Failed to allocate a 67100684 byte allocation with 16777216 free bytes and 62MB until OOM
                                                                       at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
                                                                       at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
                                                                       at com.github.barteksc.pdfviewer.util.Util.toByteArray(Util.java:37)
                                                                       at com.github.barteksc.pdfviewer.source.InputStreamSource.createDocument(InputStreamSource.java:37)
                                                                       at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:49)
                                                                       at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by barteksc** [comment]
InputStream is written to bytearray before passing to native lib, so whole file is stored in memory.

**Comment by Rdxer** [comment]
When the PDF file is large. The document has several hundred pages. After you open it, scroll through it, and after you turn over the pages, memory starts to jump, and then OOM. How to solve this problem. big shot. Save me ~
