### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by janvde** [barteksc/AndroidPdfViewer#169]
`
Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
android.os.AsyncTask$3.done (AsyncTask.java:325)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
java.util.concurrent.FutureTask.setException (FutureTask.java:223)
java.util.concurrent.FutureTask.run (FutureTask.java:242)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)
arrow_drop_down
`

`
Caused by java.lang.ArrayIndexOutOfBoundsException: length=109; index=-1
java.util.ArrayList.fastRemove (ArrayList.java:531)
java.util.ArrayList.remove (ArrayList.java:514)
com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground (RenderingAsyncTask.java:78)
com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground (RenderingAsyncTask.java:31)
android.os.AsyncTask$2.call (AsyncTask.java:305)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)
`

**Comment by Kharlos** [comment]
i have the same issue :S 
#
E/UncaughtException: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                           at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:682)
                                                                           at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:63)
                                                                           at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:25)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:631)
                                                                           at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:176)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:525)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                                           at dalvik.system.NativeStart.main(Native Method)
