### ISSUE TITLE
what's wrong? ( cannot load page)

### ISSUE THREAD

**Issue by godmarvin** [barteksc/AndroidPdfViewer#212]
03-02 19:07:37.034 17817-19398/com.zdeps.app E/jniPdfium: Loaded page is null
03-02 19:07:37.034 17817-19398/com.zdeps.app E/AndroidRuntime: FATAL EXCEPTION: PDF renderer
                                                               Process: com.zdeps.app, PID: 17817
                                                               java.lang.IllegalStateException: cannot load page
                                                                   at com.shockwave.pdfium.PdfiumCore.nativeLoadPage(Native Method)
                                                                   at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:134)
                                                                   at com.github.barteksc.pdfviewer.RenderingHandler.proceed(RenderingHandler.java:84)
                                                                   at com.github.barteksc.pdfviewer.RenderingHandler.handleMessage(RenderingHandler.java:70)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)

I user the demo of your,it can open this file,but i can"t open it;

**Comment by 1stmetro** [comment]
Loaded page is null <-- this says the page is null, could the file or path is not quite right..

Print the error in full it will show the line in your code that is at fault.

**Comment by godmarvin** [comment]
thanks   ,I'm resolved ,the pdf file only two pages ,i remove this mothod  ".pages(0, 2, 1, 3, 3, 3)"that open success;can you tell me that mean?

**Comment by maroney-tm** [comment]
@1stmetro, what do you mean by "print the error in full"? Al I get is the stacktrace at the time of the crash.
