### ISSUE TITLE
I cant load file

### ISSUE THREAD

**Issue by Kharlos** [barteksc/AndroidPdfViewer#214]
E/UncaughtException: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:682)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:63)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:25)
at android.os.AsyncTask.finish(AsyncTask.java:631)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
at dalvik.system.NativeStart.main(Native Method)

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                        at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:682)
                                                                        at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:63)
                                                                        at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:25)
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:631)
                                                                        at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:176)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:525)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by 1stmetro** [comment]
If you post your code it might help more than the actual errors, 

The error is in an array, i would guess you are not locating the file to load in pdfView and it fails with array error since the array would be zero as shown in the error log, 

Post your code for more assistance.

**Comment by barteksc** [comment]
Closing due to author's inactivity

**Comment by zhangxu0401** [comment]
remove .pages()。
