### ISSUE TITLE
Unknown Crash of NullPointerException

### ISSUE THREAD

**Issue by abbasiehsan1991** [barteksc/AndroidPdfViewer#280]
Hello I need to open pdf files from SDCard and I got their getAbsolutePath and create a File with it, and try to open it ,but when i want to use this library like below codes i will get error of : 

```
04-30 10:07:55.656 22079-22079/? E/Zygote: MountEmulatedStorage()
04-30 10:07:55.656 22079-22079/? E/Zygote: v2
04-30 10:07:55.661 22079-22079/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
04-30 10:07:56.471 22079-22079/simplevideoplayer.app.codenevisha.com.videoplayer E/ViewSystem: ViewRootImpl #2 Surface is not valid.
04-30 10:08:00.911 22079-22079/simplevideoplayer.app.codenevisha.com.videoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                   Process: simplevideoplayer.app.codenevisha.com.videoplayer, PID: 22079
                                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{simplevideoplayer.app.codenevisha.com.videoplayer/simplevideoplayer.app.codenevisha.com.videoplayer.PDFActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.barteksc.pdfviewer.PDFView$Configurator com.github.barteksc.pdfviewer.PDFView.fromFile(java.io.File)' on a null object reference
                                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
                                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
                                                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.barteksc.pdfviewer.PDFView$Configurator com.github.barteksc.pdfviewer.PDFView.fromFile(java.io.File)' on a null object reference
                                                                                                       at simplevideoplayer.app.codenevisha.com.videoplayer.PDFActivity.onCreate(PDFActivity.java:39)
                                                                                                       at android.app.Activity.performCreate(Activity.java:6289)
                                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758) 
                                                                                                       at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                       at android.os.Looper.loop(Looper.java:145) 
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
```

and this is my code: 
```
public class PDFActivity extends AppCompatActivity {

  PDFView pdfView;
  String pdfFile;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_pdf);


    Bundle bundle = getIntent().getExtras();
    if (bundle != null) {
      pdfFile =  bundle.getString(Const.PDF_PATH);
    }

    File file = new File(pdfFile);
    
    pdfView.fromFile(file)
      .enableSwipe(true)
      .load();


  }

}
```
Thank you for your answers

**Comment by 1stmetro** [comment]
The sd card paths change from os version to os version,  if your locate the pdf with a file manager on the device and compare with your app path they should be the same it's a good place to start.

**Comment by barteksc** [comment]
Did you read stacktrace? pdfView is null

**Comment by 1stmetro** [comment]
I never bothered to scroll, oops!

**Comment by barteksc** [comment]
Closing due to author's inactivity

**Comment by roidev** [comment]
I have the same problem. How did you solve this issue. Why pdfView is null? thanks in advance

**Comment by 1stmetro** [comment]
Compare your actual path against your coded path

**Comment by awaisakhtar2017** [comment]
same problem  anyone can guide me ?
