### ISSUE TITLE
The PdfViewer crashes on HUAWEI G750-T01 and  vivo Y13

### ISSUE THREAD

**Issue by yushuyou** [barteksc/AndroidPdfViewer#352]
Detail:

Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: find_library(linker.cpp:905): "/data/app-lib/com.xxx.xxx-1/libjniPdfium.so" failed to load previously
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:514)
at com.shockwave.pdfium.PdfiumCore.<clinit>(PdfiumCore.java)
at com.github.barteksc.pdfviewer.PDFView.<init>(PDFView.java)

**Comment by barteksc** [comment]
How do you include library?

**Comment by yushuyou** [comment]
I user "Central Application Tracking" Catching ,only the two phones crashed

**Comment by barteksc** [comment]
I am not asking what other libraries do you use, but how do include AndroidPdfViewer library

**Comment by yushuyou** [comment]
Add compile 'com.github.barteksc:android-pdf-viewer:2.5.1' to build.gradle:

**Comment by KnIfER** [comment]
where to find/make/build/download libjniPdfium.so?
i am using this on eclipse

**Comment by KnIfER** [comment]
ndk-build in PdfiumAndroid-master,and it will be the solution.
amazing!
