### ISSUE TITLE
Fatal Exception: java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by KrawczykPawel** [barteksc/AndroidPdfViewer#356]
`Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.github.barteksc.pdfviewer.PDFView.loadPageByOffset(PDFView.java:1009)
       at com.github.barteksc.pdfviewer.DragPinchManager.onScroll(DragPinchManager.java:136)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:607)
       at com.github.barteksc.pdfviewer.DragPinchManager.onTouch(DragPinchManager.java:200)
       at android.view.View.dispatchTouchEvent(View.java:9297)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)`

**Comment by MaciejCzekanski** [comment]
I have the same issue. Workaround is to disable pdfView before content is loaded, and reenable it in onRender().

**Comment by volic** [comment]
+1

**Comment by 867588763** [comment]
+1,I have the same issue

**Comment by 18872731525** [comment]
+1 the same issue i meet

**Comment by barteksc** [comment]
Should be resolved in 2.7.0
