### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#375]
I found an issue with java.util.ConcurrentModificationException around line 667, had to put it in a catch to resolve it.

for (Integer page : onDrawPagesNums) {
                drawWithListener(canvas, page, onDrawAllListener);
            }
            onDrawPagesNums.clear();

Basically i'm using the .onDrawAll method and firing my event on the first time this event is started and as i reload various pdf this error will happen,

The error log is as follows....

E/UncaughtException: java.util.ConcurrentModificationException
                                                                                        at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                                        at com.github.barteksc.pdfviewer.PDFView.onDraw(PDFView.java:662)
                                                                                        at android.view.View.draw(View.java:17524)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16517)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3230)
                                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3029)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2611)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7520)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:622)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

********************************************************** it then continues into another error as below..

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: sample.app.com, PID: 3861
java.util.ConcurrentModificationException
                                                                                     at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                                     at com.github.barteksc.pdfviewer.PDFView.onDraw(PDFView.java:662)
                                                                                     at android.view.View.draw(View.java:17524)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16517)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3910)
                                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3890)
                                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16477)
                                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:3230)
                                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3029)
                                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2611)
                                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1524)
                                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7520)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:622)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by barteksc** [comment]
Catching `ConcurrentModificationException` is bad idea, what is your code?

**Comment by 1stmetro** [comment]
Basically I catch an image on the initial drawing of the off and save it also have a watermark and occassionaly it dies hence the catch.

Any suggestions ?

**Comment by 1stmetro** [comment]
Can i ask why catching is a bad move on concurrentMod.... ?

**Comment by barteksc** [comment]
`ConcurrentModificationException` should never be thrown in correct code, so catching it is only temporary workaround
