### ISSUE TITLE
App crushing

### ISSUE THREAD

**Issue by pstuashiqcse** [barteksc/AndroidPdfViewer#40]
I'm getting following error and app become crushed while swipe 30-35 page of any pdf file:

AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.example.pdf, PID: 11626
                                                                  java.lang.ArithmeticException: divide by zero
                                                                      at

**Comment by pstuashiqcse** [comment]
Sometimes this error occurring after swipe few page, I think its a memory issue. Is there any workaround to control memory consumption??

PID: 29307
                                                                  java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.NullPointerException
                                                                      at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:103)
                                                                      at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:67)
                                                                      at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:31)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841)

**Comment by barteksc** [comment]
It's not memory issue, I will fix it soon.

**Comment by barteksc** [comment]
Should be fixed in 1.4.

**Comment by Hardikkamothi** [comment]
Whether this issue is fixed in 1.5.0 ? Please confirm.

**Comment by barteksc** [comment]
As I wrote, it was fixed in 1.4
