### ISSUE TITLE
sometimes crash with:An error occured while executing doInBackground

### ISSUE THREAD

**Issue by chendd** [barteksc/AndroidPdfViewer#43]
FATAL EXCEPTION: AsyncTask #7
                                                                    Process: com.dkhs.portfolio, PID: 11044
                                                                    java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)
                                                                     Caused by: java.lang.NullPointerException
                                                                        at com.github.barteksc.pdfviewer.RenderingAsyncTask.proceed(RenderingAsyncTask.java:103)
                                                                        at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:67)
                                                                        at com.github.barteksc.pdfviewer.RenderingAsyncTask.doInBackground(RenderingAsyncTask.java:31)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                        at java.lang.Thread.run(Thread.java:841)

**Comment by barteksc** [comment]
I will fix it soon.

**Comment by barteksc** [comment]
Should be fixed in 1.4.

**Comment by chendd** [comment]
thx
