### ISSUE TITLE
Getting blank Layout.

### ISSUE THREAD

**Issue by Ahmedmuhammed** [barteksc/AndroidPdfViewer#432]
When I include XML code in my Layout. the layout disappears and shows nothing.

**Comment by barteksc** [comment]
Please explain and show your code

**Comment by Ahmedmuhammed** [comment]
When adding XML code which is explained in library usage. my Relativelayout
![pdf](https://user-images.githubusercontent.com/15983788/32018067-0088d45e-b9c9-11e7-8499-ab6a6604174a.jpg)
 is getting empty and shows nothing anymore. here is my code:

**Comment by Ahmedmuhammed** [comment]
![books](https://user-images.githubusercontent.com/15983788/32018140-36dd46a2-b9c9-11e7-856f-ba2141ae6e84.png) here is my layout without library xml code

**Comment by maroney-tm** [comment]
Looks like you're getting a rendering issue in your preview. Does android studio give you any errors? Also try setting your relative layout constraints.
android:layout_alignParentStart="true"
android:layout_alignParentEnd="true"

**Comment by 1stmetro** [comment]
I always get rendering issues so I don't actually use it....

**Comment by Neogene** [comment]
Me toot, Android Studio 3.

`java.lang.NullPointerException
	at com.github.barteksc.pdfviewer.PDFView.computeScroll(PDFView.java:577)
	at android.view.View.draw(View.java:18933)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1587)
	at android.view.View.draw(View.java:19060)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1229)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw(View.java:19060)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw(View.java:19060)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw(View.java:19195)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:403)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:541)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:424)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:108)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$5(RenderTask.java:757)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by invisible66** [comment]
Yess me too..

**Comment by Eastwind-janith** [comment]
me too

**Comment by Ali-Haider8** [comment]
me to

**Comment by barteksc** [comment]
Fixed in version 2.8.1
