### ISSUE TITLE
Issue after version upgrade to 2.8.0

### ISSUE THREAD

**Issue by HashirLabs** [barteksc/AndroidPdfViewer#442]
Hi

I am getting below exception when i upgraded to version 2.8.0 from 2.7.0.

` java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
                                                                             at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
                                                                             at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:113)
                                                                             at com.github.barteksc.pdfviewer.source.FileSource.createDocument(FileSource.java:38)`

I reverted back to version 2.7.0 where its working fine. Please see if you can help
There are no changes either in the method parameter or the file i am opening, the same issue observed despite trying other pdfs as well, and it worked for all of them when i reverted the version

**Comment by 1stmetro** [comment]
No issues here

**Comment by barteksc** [comment]
I cannot reproduce it
