### ISSUE TITLE
AndroidPdfViewer 3.0.0-beta - bug reports & feature improvements

### ISSUE THREAD

**Issue by barteksc** [barteksc/AndroidPdfViewer#447]
Today version 3.0.0-beta.1 was released, which has support for different page sizes, links and 3 modes of fitting document to screen.

Please report bugs and improvements for added features.
Please do not request new features, as current target is to release stable 3.0.0.

**Comment by 1stmetro** [comment]
Could we do away with background color being used as the page border..... i hve to modify the code on every update...

Will load up beta shortly.

**Comment by barteksc** [comment]
Pages don't have borders. If you talk about spacing, the spacing is gap, and through the gap you see what is behind the document.

**Comment by 1stmetro** [comment]
Yeah the spacing.

I have to mod source to draw the space as sometimes a large pdf will leave a coloured page and also the scroll in from the right pdf shows a coloured page sliding into view etc.

**Comment by 1stmetro** [comment]
Side swipes in landscape view leave a large white border on the right side of the page..

Perhaps someone else could also confirm this.

**Comment by 1stmetro** [comment]
Side swipe in landscape view i have a large white space on the right side, anyone else have the same issue ?

**Comment by barteksc** [comment]
@1stmetro Please post your code, screenshot and PDF document if possible.

**Comment by albakaly** [comment]
Zoom in is not work  if I get full zoom.  The pdf blurred and never cleared unless I zoom out.

**Comment by 1stmetro** [comment]
Any pdf i use in this mode gives me the white gap but you can see page 2 coming into view

Also notice the page number object floats down.

![device-2017-11-13-201437](https://user-images.githubusercontent.com/21983778/32746990-4c2fc83c-c8af-11e7-9409-73bdc082a014.png)


![device-2017-11-13-201058](https://user-images.githubusercontent.com/21983778/32746871-e8571c7a-c8ae-11e7-983d-9fcadf62e4c8.png)

**Comment by barteksc** [comment]
@1stmetro please post you code

**Comment by 1stmetro** [comment]
just playing with source

I believe the default is pageFitPolicy = FitPolicy.WIDTH; so in landscape mode does it remain in this policy?

just trying if in landscape change fitpolicy to etc.... but it doesnt center the pdf but i can make the gap narrower

**Comment by 1stmetro** [comment]
Okay if i change the policy to .pageFitPolicy(FitPolicy.HEIGHT) then i get the following as shown, the screen is in landscape, no code changes just changing the policy when loading a normal pdf.

![device-2017-11-13-205036](https://user-images.githubusercontent.com/21983778/32748544-7a6f6a0e-c8b4-11e7-975a-ae4700809dea.png)

**Comment by barteksc** [comment]
@1stmetro You are using horizontal swipe and scroll handle is in position like in vertical mode?

**Comment by albakaly** [comment]
Here is another issue, this happen when I close pdf doc.
When I press back sometimes not always this happens.
I couldn't  find which activity  is , or which line in  the library.
Here is stack trace. 
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.transformMatrixToGlobal(android.graphics.Matrix)' on a null object reference
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.GhostView.calculateMatrix(GhostView.java:95)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.app.ActivityTransitionCoordinator$GhostViewListeners.onPreDraw(ActivityTransitionCoordinator.java:845)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:921)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2166)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6641)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.Choreographer.doCallbacks(Choreographer.java:590)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.Choreographer.doFrame(Choreographer.java:560)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.os.Handler.handleCallback(Handler.java:739)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.os.Looper.loop(Looper.java:145)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:5942)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at java.lang.reflect.Method.invoke(Native Method)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at java.lang.reflect.Method.invoke(Method.java:372)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
11-14 00:04:46.496 16635 16635 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
11-14 00:04:48.196 17362 17362 E   SELinux                                      [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-14 00:04:49.576 17362 17383 E   OpenGLRenderer                               SFEffectCache:clear(), mSize = 0
11-14 00:14:38.660 23790 23790 E   SELinux com.mycompany.myapp2                 [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-14 00:14:43.520 23790 23790 E   libEGL com.mycompany.myapp2                  call to OpenGL ES API with no current context (logged once per thread)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          FATAL EXCEPTION: main
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          Process: com.mycompany.myapp2, PID: 23790
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.transformMatrixToLocal(android.graphics.Matrix)' on a null object reference
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.app.EnterTransitionCoordinator.setSharedElementMatrices(EnterTransitionCoordinator.java:648)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.app.EnterTransitionCoordinator.access$100(EnterTransitionCoordinator.java:42)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.app.EnterTransitionCoordinator$3.onPreDraw(EnterTransitionCoordinator.java:208)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:921)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2166)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6641)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.Choreographer.doCallbacks(Choreographer.java:590)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.Choreographer.doFrame(Choreographer.java:560)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.os.Handler.handleCallback(Handler.java:739)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.os.Looper.loop(Looper.java:145)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at android.app.ActivityThread.main(ActivityThread.java:5942)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at java.lang.reflect.Method.invoke(Native Method)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at java.lang.reflect.Method.invoke(Method.java:372)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
11-14 00:15:41.850 23790 23790 E   AndroidRuntime com.mycompany.myapp2          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
11-14 00:14:38.660 23790 23790 E   SELinux com.mycompany.myapp2                 [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
11-14 00:14:43.520 23790 23790 E   libEGL com.mycompany.myapp2                  call to OpenGL ES API with no current context (logged once per thread)

**Comment by 1stmetro** [comment]
Horizontal swipe in portrait or landscape i get the gap in height policy its better but the policy appears to be static as it doesn't change when changing orientation i'm sure you get what i mean now.

Also the maximum zoom does not final render,

**Comment by 1stmetro** [comment]
albakaly if its an activity issue that you cant go back to that would'nt be a pdf view issue.

**Comment by albakaly** [comment]
It is not an activity  issue as there is no problem  with previous version  of this library,

**Comment by barteksc** [comment]
@1stmetro I cannot reproduce this behavior, could you send PDF document?

**Comment by albakaly** [comment]
I think it is as you said problem  with activity  shared elements  not from the library.

Thanks

**Comment by 1stmetro** [comment]
[LiIon_tut.pdf](https://github.com/barteksc/AndroidPdfViewer/files/1468716/LiIon_tut.pdf)

Any pdf's seem to do the same after changing to horizontal swipes using code below, 

if (pdfView.isSwipeVertical()) {
                pdfView.setSwipeVertical(false);
                pdfView.jumpTo(pdfView.getCurrentPage());
                pdfView.resetZoom();

            }
            else{
                pdfView.setSwipeVertical(true);
                pdfView.jumpTo(pdfView.getCurrentPage());
                pdfView.resetZoom();
            }

**Comment by barteksc** [comment]
@1stmetro So the problem is that you are changing swipe to horizontal after loading document. I forgot to make `setSwipeVertical()` private. It requires to much calculations to use this method. Swipe mode must be set using `.swipeHorizontal()` when loading document.

**Comment by 1stmetro** [comment]
Okay so you cannot change the swipe after the document has been loaded?

**Comment by albakaly** [comment]
@barteksc have you into the zoom issue?

**Comment by barteksc** [comment]
@1stmetro You cannot. It shouldn't be possible either in 2.X versions, but it is my mistake.
@albakaly I reproduced this issue, so it will be fixed in next release

**Comment by barteksc** [comment]
Beta 3.0.0-beta.2 released with zoom fixes.

**Comment by 1stmetro** [comment]
just upgraded to beta 2 i see you fixed my loop hole issue....

Now i will have to write a fix to show mini pages....

**Comment by albakaly** [comment]
@barteksc  Thank you so much.
Zooming is great .

**Comment by barteksc** [comment]
@1stmetro what is loop hole issue?

**Comment by 1stmetro** [comment]
the if (pdfView.isSwipeVertical()) it is now private.

tell how do you get the total width of the whole canvas ?

dstRect.right
dstRect.bottom

**Comment by barteksc** [comment]
`.isSwipeVertical()` is public, not private. 
`PdfFile#getDocLen()` gives you current document length (height in vertical mode, width in horizontal) and `PdfFile#getMaxPageSize()` gives you size of page with maximum width (in vertical mode) or maximum height (in horizontal mode)

**Comment by barteksc** [comment]
Version 3.0.0-beta.3 released with fixed bug preventing `OnErrorListener` from being called.

**Comment by 1stmetro** [comment]
Getting it now, Thanks !

**Comment by 1stmetro** [comment]
Maybe worth closing this one and reopen a 3.0.0-beta 3 

I have an issue with i believe different page sizes, if offsets from the left side so the page is not fitting to width.

If i find a pdf i can send i will pop it on here so you can test.

**Comment by barteksc** [comment]
@1stmetro I've opened both documents and don't understand where is the issue

**Comment by 1stmetro** [comment]
maybe not a good example, this image left side pic shows the border i mean but if i drag from right to left i then you see whole page, whole pdf is the same.


![post](https://user-images.githubusercontent.com/21983778/32985930-fc54b47c-ccbd-11e7-9d2d-1adfe28f4f2c.png)

**Comment by barteksc** [comment]
@1stmetro What does it mean "whole pdf is the same"?

**Comment by 1stmetro** [comment]
I will look at the spec of the pdf but for some reason it offsets this pdf and doesn't resize correctly.

**Comment by barteksc** [comment]
@1stmetro Currently I don't understand anything from your bug report

**Comment by albakaly** [comment]
I noticed that  when I scroll between pages , something like flashes appears. Example, I have two pages when I scroll from the first page to second , the second page jumps to the screen like flash, like it blurred, however the half of the first page still in the screen .
In brief, scrolling is not soomth between pages, when you scroll to half of the first page the second page jumps to screen like flash or blurred.  So when you are reading at the mid of any page , the next page jump to the screen and you just feel like you lost and return to the previous page. It is really tiring.
Sorry if you don't understand my point.

**Comment by starnaus** [comment]
Is there a setting to show/swipe one page at a time? Centered in the view?

**Comment by barteksc** [comment]
@starnaus no, there is no such possibility

**Comment by starnaus** [comment]
Thank you for the reply. Is this feature on a roadmap for a future version?

**Comment by 1stmetro** [comment]
Download the source @starnaus and modify to how you want it to work that's what others do.

**Comment by KewalMedic** [comment]
**Unable to open Hyperlinks within pdf:** 

I am using version 3.0.0-beta.3  and below is the code to load pdf-
 _pdfView.fromFile(new File(filePath))
                .defaultPage(0)
                .scrollHandle(new DefaultScrollHandle(this))
                .pageFitPolicy(FitPolicy.BOTH)
                .spacing(10)
                .enableAnnotationRendering(true)
                .linkHandler(new DefaultLinkHandler(pdfView))
                .onError(this)
                .load();_

This the same code to load pdf as written in sample app too but its not working for hyperlinks.
Looking for the solution.

Thanks,

**Comment by Jiten-Medic** [comment]
Hi @barteksc 

We're using this library and having some major issues while URL link clicks.
No callback was fired when we click over the URL where as Dropbox and other PDF viewers opens the link of same PDF.

Lib Details : 
version 3.0.0-beta.3 

Same code as mentioned by @KewalMedic is used, please help to resolve this bug.

Below attached is the sample pdf file used for the testing.
[Get Started with Dropbox.pdf](https://github.com/barteksc/AndroidPdfViewer/files/1574032/Get.Started.with.Dropbox.pdf)


Thanks

**Comment by Jiten-Medic** [comment]
Hi @barteksc 
Have you found the reason for links not working, any timeline for the same.

Thanks

**Comment by barteksc** [comment]
@Jiten-Medic links should be fixed in 3.0.0-beta.5 version

**Comment by 1stmetro** [comment]
Thanks @barteksc now got beta 5 and working fine,

**Comment by Jiten-Medic** [comment]
Hi @barteksc 

Thanks for your update, it's working fine for hyperlinks.
But when the URL is written like text as https://google.com it doesn't takes the click and not open them.

Please look over this as well.

Regards

**Comment by barteksc** [comment]
@Jiten-Medic only urls are clickable, there is no mechanism for detecting plaintext URLs

**Comment by devi2911** [comment]
I have a pdf thats 106 MB and has got 100 pages....The PDF is viewed only for the first 5 or 6 pages and then it ends

**Comment by 1stmetro** [comment]
Can you post the pdf so I can check it?

**Comment by devi2911** [comment]
@1stmetro  sorry to have bothered you....It's working fine...silly mistake in code...cheers

**Comment by 1stmetro** [comment]
No probs...

**Comment by chiragc-wal** [comment]
Hyperlinks are not working in 3.1.0-beta.1 
Below is my code, 

pdfView.fromFile(file)
                    .enableAnnotationRendering(true)
                    .onLoad(this)
                    .scrollHandle(new DefaultScrollHandle(this))
                    .spacing(10) // in dp
                    .onPageError(this)
                    .linkHandler(new DefaultLinkHandler(pdfView)) // It's a default handler of library
                    .load();

**Comment by kuerm** [comment]
@barteksc As I wrote in https://github.com/barteksc/AndroidPdfViewer/issues/674, there's still an error in jumpTo.
I guess that if the first page has an Offset != 0, then the next ones won't be displayed correctly. I attached a sample file.
Maybe the best solution would be to set offset to 0 when loading pdf, to not have strange behaviour later in PDF management.
[offsetgreater0.pdf](https://github.com/barteksc/AndroidPdfViewer/files/5720774/offsetgreater0.pdf)

**Comment by Zongali** [comment]
Hello.
 1st, thank you for this nice project.

 It will be great if you can add the feature to control the page navigation direction; LeftToRight or RightToLeft.
thanks again.
