### ISSUE TITLE
load pdf error java.io.FileNotFoundException: Permission denied

### ISSUE THREAD

**Issue by IamOnkar** [barteksc/AndroidPdfViewer#449]
not loading pdf file form download folder on mobile app.
giving following error,working on samsung device only with kitkat 4.2.2

ERROR DETAIL
---------------------------------------------------------------------------------------------------------------------
E/PDFView: load pdf error
                                                            java.io.FileNotFoundException: Permission denied
                                                                at android.os.Parcel.openFileDescriptor(Native Method)
                                                                at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:252)
                                                                at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:198)
                                                                at com.github.barteksc.pdfviewer.source.FileSource.createDocument(FileSource.java:37)
                                                                at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:49)
                                                                at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by barteksc** [comment]
So there is permissions problem, as you can read in stacktrace...

**Comment by 1stmetro** [comment]
The answer is in the question... file not found use a string as the path then once you have that working move it to a programmable path, walk before you run as they say.

E/PDFView: load pdf error
java.io.FileNotFoundException: Permission denied
