### ISSUE TITLE
NPE PdfFile.getMaxPageWidth() at PDFView.canScrollHorizontally(PDFView.java:450)

### ISSUE THREAD

**Issue by mock-duck** [barteksc/AndroidPdfViewer#468]
`12-12 10:44:51.946 15110-15110/de.epost.safe E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.my.app, PID: 15110
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'float com.github.barteksc.pdfviewer.PdfFile.getMaxPageWidth()' on a null object reference
                                                                   at com.github.barteksc.pdfviewer.PDFView.canScrollHorizontally(PDFView.java:450)
                                                                   at android.support.v4.view.ViewCompatICS.canScrollHorizontally(ViewCompatICS.java:31)
                                                                   at android.support.v4.view.ViewCompat$ICSViewCompatImpl.canScrollHorizontally(ViewCompat.java:1270)
                                                                   at android.support.v4.view.ViewCompat.canScrollHorizontally(ViewCompat.java:1726)
                                                                   at android.support.v4.view.ViewPager.canScroll(ViewPager.java:2646)
                                                                   at android.support.v4.view.ViewPager.canScroll(ViewPager.java:2637)
                                                                   at android.support.v4.view.ViewPager.canScroll(ViewPager.java:2637)
                                                                   at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1999)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                   at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                   at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                   at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                               	at android.view.In`

Steps to reproduce:
Load a lager pdf file and start swiping before it*s completely loaded

I am using current 3.0.0-beta.3 version

**Comment by barteksc** [comment]
Thanks, I will fix it in next release

**Comment by barteksc** [comment]
Fixed in 3.0.0-beta.4
