### ISSUE TITLE
APP crash when open PDF file by installed  Generate Singed APK

### ISSUE THREAD

**Issue by caigxfj** [barteksc/AndroidPdfViewer#491]
Thank you for reading my question.
when i use android phone to run the app in debug mode, using PDFView like ： pdfView.fromStream (inputStream)
                         .defaultPage (0)
                         .onLoad (...)
                         .onError (...)
                         .enableAnnotationRendering (true)
                         .scrollHandle (new DefaultScrollHandle (PreviewActivity.this))
                         .load ();
and it is normal to open pdf file, but after I Generate Singed APK, and installed the APK,then open pdf file the app crash.
below is the logcat:
W/WindowAnimator: Failed to dispatch window animation state change.
                                                 android.os.DeadObjectException
                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                     at android.os.BinderProxy.transact(Binder.java:505)
                                                     at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                     at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:313)
                                                     at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:786)
                                                     at com.android.server.wm.WindowAnimator.access$000(WindowAnimator.java:59)
                                                     at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:134)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:698)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:630)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
                                                     at android.os.Handler.handleCallback(Handler.java:743)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:150)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                     at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by caigxfj** [comment]
i change 3.0.0 to 2.8.2，and rebuild，then installed  Generate Singed APK，there is no this problem any more

**Comment by caigxfj** [comment]
oh，I found the reason，because proguard-rules.pro...

**Comment by ajaydhadhal1111** [comment]
Thanks it Work for me.
