### ISSUE TITLE
It will crash when recursiveGetBookmark method is called

### ISSUE THREAD

**Issue by pengchenwei** [barteksc/AndroidPdfViewer#521]
![14740 1055x391 32](https://user-images.githubusercontent.com/17327531/35137598-2740b7ca-fd25-11e7-93da-4519559e70fa.png)
sometimes, when there are too many bookmarks in the pdf file, the app will carsh. The log I got as follow:
  FATAL EXCEPTION: main
                                                                                       Process: com.example.administrator.myapplication, PID: 9707
                                                                                       java.lang.StackOverflowError
                                                                                           at java.util.ArrayList.<init>(ArrayList.java:81)
                                                                                           at com.shockwave.pdfium.PdfDocument$Bookmark.<init>(PdfDocument.java:56)
                                                                                           at com.shockwave.pdfium.PdfiumCore.recursiveGetBookmark(PdfiumCore.java:305)

I've been search on the internet , it seems that no one have met this problem. And some advises are increase stack size by using -Xss1024K...But it dose't work at all , could you give me some idea to solve  this problem? And by the way, this problem only exist on my Android 4.4.4 version devices, not on the 5.0 devices. Thanks again!

**Comment by mmdet** [comment]
唉

**Comment by barteksc** [comment]
@mmdet there are people all around the world, please use english only
