### ISSUE TITLE
Open document failed

### ISSUE THREAD

**Issue by elsennov** [barteksc/AndroidPdfViewer#6]
Hi, recently i got this error

```
com.shockwave.pdfium.PdfOpenException: Open document failed
at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:72)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:61)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:32)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
```

Do you have any idea why? How could i fix this? Thanks

**Comment by barteksc** [comment]
Show some code, there is nothing useful in this stacktrace

**Comment by elsennov** [comment]
```
pdfView.fromFile(pdfFile)
                .defaultPage(DEFAULT_PAGE)
                .showMinimap(false)
                .enableSwipe(true)
                .onLoad(nbPages -> LogUtils.debug(TAG, "onLoad PDF"))
                .onPageChange((page, pageCount) -> LogUtils.debug(TAG, "onPageChange PDF"))
                .onError(throwable -> LogUtils.error(TAG, "Error in opening PDF", throwable))
                .load();
```

**Comment by barteksc** [comment]
Does pdfFile exist (by using `pdfFile.exists()`)?

**Comment by elsennov** [comment]
Yes, absolutely i defense the code before passed it

**Comment by barteksc** [comment]
What is the path of file? Internal memory, physical SD card?

**Comment by elsennov** [comment]
The root is Environment.getExternalStorageDirectory();
This error happened intermittently.

**Comment by barteksc** [comment]
It must be issue in native lib, I'll take a look at it yesterday, but it looks strange

**Comment by elsennov** [comment]
Okay thank you

**Comment by jayDLabs** [comment]
Hi, same error here :
`D/jniPdfium: Init FPDF library
D/jniPdfium: File Size: 295
D/jniPdfium: Destroy FPDF library
E/jniPdfium: Error loading document from file map
E/jniPdfium: Last Error: 3
E/com.shockwave.pdfium.PdfiumCore: Open document failed
E/PDFView: load pdf error
	com.shockwave.pdfium.PdfOpenException: Open document failed
	    at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:72)
	    at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:61)
	    at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:32)
	    at android.os.AsyncTask$2.call(AsyncTask.java:287)
	    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	    at java.lang.Thread.run(Thread.java:856)`

Looks like getNumFd() catched an IllegalAccessException and returned -1

**Comment by barteksc** [comment]
@jayDLabs You got Pdfium error 3, it means that PDF is corrupted or some other unknown error occurred. Check if you can open this file in another reader

**Comment by jayDLabs** [comment]
Exact, the PDF is corrupted, something went wrong when downloading it on my side, my bad.
Thank you !

**Comment by barteksc** [comment]
@elsennov please check if version 1.1.0 fixes this issue

**Comment by elsennov** [comment]
@barteksc ok

**Comment by elsennov** [comment]
Seems it has been solved. No crash occurred! Thanks @barteksc
