### ISSUE TITLE
Nullpointer exception on page load

### ISSUE THREAD

**Issue by kaiske56** [barteksc/AndroidPdfViewer#60]
Hi
@barteksc Could you please help me with this issue

E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to read from field 'long
                                     com.shockwave.pdfium.PdfDocument.mNativeDocPtr' on a null object reference
                                     at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:120)
                                     at com.github.barteksc.pdfviewer.PDFView.loadPage(PDFView.java:695)
                                     at com.github.barteksc.pdfviewer.PDFView.loadPages(PDFView.java:653)
                                     ...

**Comment by janvde** [comment]
Keep getting this one too.

`Exception java.lang.NullPointerException: Attempt to read from field 'long 
com.shockwave.pdfium.PdfDocument.mNativeDocPtr' on a null object reference
com.shockwave.pdfium.PdfiumCore.openPage (PdfiumCore.java:134)
com.github.barteksc.pdfviewer.PDFView.loadPage (PDFView.java:699)
com.github.barteksc.pdfviewer.PDFView.loadPages (PDFView.java:657)
com.github.barteksc.pdfviewer.AnimationManager$FlingAnimation.onAnimationEnd (AnimationManager.java:182)`
