### ISSUE TITLE
Crashes on version 3.1.0-beta.1 from Fabric on Android Galaxy Devices.

### ISSUE THREAD

**Issue by gautam2682** [barteksc/AndroidPdfViewer#624]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.barteksc.pdfviewer.f.a(float, float)' on a null object reference
       at com.github.barteksc.pdfviewer.d.a(Unknown Source)
       at com.github.barteksc.pdfviewer.d.onSingleTapConfirmed(Unknown Source)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:312)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Flamedek** [comment]
Investigating the obfuscated trace, the crash could be on DragPinchManager line 88.  
Here, in `checkLinkTapped`, we call `pdfFile.getPageAtOffset(float, float)` while pdfFile may be null.

**Comment by gautam2682** [comment]
Please tell me where to make changes in the code because its happening more often and I want to fix it fast.

**Comment by YuriyBereguliak** [comment]
Crash at this line, because `pdfFile == null`: 
`int page = pdfFile.getPageAtOffset(pdfView.isSwipeVertical() ? mappedY : mappedX,pdfView.getZoom());`
