### ISSUE TITLE
Native crash on PdfiumCore.nativeLoadPage with IllegalStateException and message "can not load page" 

### ISSUE THREAD

**Issue by aalap03** [barteksc/AndroidPdfViewer#692]
Hi, I got crash email from crashlytics for a client user with following stacktrace. I tried reproducing by opening multiple PDFs, but I could not. I tried looking at the source code of the mentioned classes but I am not able to figure out what might have gone wrong. 

The attached is the txt file downloaded from crashlytics for complete stacktrace and these are the logs in brief to understand.

**OS Version: 8.0.0**
**Device: SM-A320FL**
**library version: 2.5.1**

    `#0. Crashed: PDF renderer
       at com.shockwave.pdfium.PdfiumCore.nativeLoadPage(PdfiumCore.java)
       at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:134)
       at com.github.barteksc.pdfviewer.RenderingHandler.proceed(RenderingHandler.java:89)
       at com.github.barteksc.pdfviewer.RenderingHandler.handleMessage(RenderingHandler.java:71)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
    --

    Fatal Exception: java.lang.IllegalStateException: cannot load page
       at com.shockwave.pdfium.PdfiumCore.nativeLoadPage(PdfiumCore.java)
       at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:134)
       at com.github.barteksc.pdfviewer.RenderingHandler.proceed(RenderingHandler.java:89)
       at com.github.barteksc.pdfviewer.RenderingHandler.handleMessage(RenderingHandler.java:71)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

    #0. Crashed: PDF renderer
       at com.shockwave.pdfium.PdfiumCore.nativeLoadPage(PdfiumCore.java)
       at com.shockwave.pdfium.PdfiumCore.openPage(PdfiumCore.java:134)
       at com.github.barteksc.pdfviewer.RenderingHandler.proceed(RenderingHandler.java:89)
       at com.github.barteksc.pdfviewer.RenderingHandler.handleMessage(RenderingHandler.java:71)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
    `

[plante.com.cobalt.mobileaccess_issue_116_crash_5BB6088A0334000164A1B01218D24B8B_DNE_0_v2.txt](https://github.com/barteksc/AndroidPdfViewer/files/2446724/plante.com.cobalt.mobileaccess_issue_116_crash_5BB6088A0334000164A1B01218D24B8B_DNE_0_v2.txt)

**Comment by junaidraz1** [comment]
have you found any solution to this issue yet?
