### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.barteksc.pdfviewer.PdfFile.getPageAtOffset(float, float)' on a null object reference

### ISSUE THREAD

**Issue by yuanjl29598** [barteksc/AndroidPdfViewer#784]
lib version: com.github.barteksc:android-pdf-viewer:3.1.0-beta.1

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.barteksc.pdfviewer.PdfFile.getPageAtOffset(float, float)' on a null object reference
        at com.github.barteksc.pdfviewer.DragPinchManager.checkLinkTapped(DragPinchManager.java:88)
        at com.github.barteksc.pdfviewer.DragPinchManager.onSingleTapConfirmed(DragPinchManager.java:69)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mujeebrahaman** [comment]
EXCEPTION
java.lang.NullPointerException

Attempt to invoke virtual method 'int com.github.barteksc.pdfviewer.PdfFile.getPageAtOffset(float, float)' on a null object reference

**Comment by patelkathan** [comment]
getting same error 

>     java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.barteksc.pdfviewer.PdfFile.getPageAtOffset(float, float)' on a null object reference

Any solution in newer release ?

**Comment by jonas-weinhardt** [comment]
Im getting the same error. I was using version 2.8.2 so I upgraded to the newest beta version 3.2.0-beta.1. It looked like this solved the problem for me, but I then got the error on devices that worked befor. So no matter wich version I am using, I get this Error on some devices.

**Comment by odemolliens** [comment]
same here:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.barteksc.pdfviewer.PdfFile.getPageAtOffset(float, float)' on a null object reference
       at com.github.barteksc.pdfviewer.DragPinchManager.checkLinkTapped + 88(DragPinchManager.java:88)
       at com.github.barteksc.pdfviewer.DragPinchManager.onSingleTapConfirmed + 69(DragPinchManager.java:69)

**Comment by ricardo-fadini-inventsys** [comment]
Same here.

**Comment by thaiquoctoanvn** [comment]
I also had the same problem. After a few day diving in my issue, I realized that the problem occurs from click event. I don't know why but in my case the view parameter from the pdfView.onClickListener cannot be casted to PdfViewer type then it made a fatal crash and I just need to add an if clause to solve the error. Additionally, you would add a default link handler to prevent some unexpected errors. I hope this information might be helpful for someone.
