### ISSUE TITLE
NPE at DefaultScrollHandle.java:106

### ISSUE THREAD

**Issue by xingjiyuan** [barteksc/AndroidPdfViewer#81]
E/PDFView: load pdf error
                                                               java.io.IOException: cannot create document: File not in PDF format or corrupted.
                                                                   at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
                                                                   at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:105)
                                                                   at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:61)
                                                                   at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:30)
                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:818)
08-29 13:01:12.633 23109-23109/com.moer.moerfinance D/ActivityThread: SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@3123f4f7
08-29 13:01:12.682 23109-23220/com.moer.moerfinance D/OpenGLRenderer: Flushing caches (mode 0)
08-29 13:01:12.682 23109-23220/com.moer.moerfinance D/OpenGLRenderer: Flushing caches (mode 0)
08-29 13:01:12.683 23109-23220/com.moer.moerfinance D/GraphicBuffer: unregister, handle(0x55962c0430) (w:554 h:345 s:576 f:0x1 u:0x000b00)
08-29 13:01:12.683 23109-23220/com.moer.moerfinance D/IMGSRV: gralloc_unregister_buffer:1503: ID=778379 ref=0
08-29 13:01:12.693 23109-23109/com.moer.moerfinance D/AndroidRuntime: Shutting down VM
08-29 13:01:12.746 23109-23109/com.moer.moerfinance E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.moer.moerfinance, PID: 23109
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent com.github.barteksc.pdfviewer.PDFView.getParent()' on a null object reference
                                                                          at com.github.barteksc.pdfviewer.scroll.DefaultScrollHandle$2.run(DefaultScrollHandle.java:106)
                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5552)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by mikemike396** [comment]
I am getting the exact same crash. Some details from Crashlytics
Device: Redmi Note 3
OS: 5.1.1

Thanks

**Comment by barteksc** [comment]
Ok, I will look at this

**Comment by barteksc** [comment]
Check version 2.0.3, it fixes this issue.

**Comment by mikemike396** [comment]
Thanks for the quick fix! I am not able to reproduce the crash just something that I saw come through on Crashlytics from a user. I will update to this version and post back if I find the crash again.

**Comment by scrylove** [comment]
I also encountered the same problem, did not expect to have been corrected, thanks to!

**Comment by scrylove** [comment]
This exception is still there, but not collapse, but PDF can not display, this is what to do?

**Comment by barteksc** [comment]
Check version 2.1.0 which introduced new fix.
