### ISSUE TITLE
Blank screen on api 29

### ISSUE THREAD

**Issue by sabih1998** [barteksc/AndroidPdfViewer#852]
I used this library and it working fine
But i realized that the component not showing pdf

**Comment by sabih1998** [comment]
Hi
i found that i'm getting this exception "
java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2) "

help me please

**Comment by tofigh77** [comment]
i have the same problem

**Comment by jrustonapps** [comment]
Also having this problem.

com.shockwave.pdfium.PdfiumCore: Native libraries failed to load - java.lang.UnsatisfiedLinkError: couldn't find "libmodpng.so"

No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)

load pdf error
    java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2)
        at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
        at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:113)
        at com.github.barteksc.pdfviewer.source.AssetSource.createDocument(AssetSource.java:41)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by farislivemaker** [comment]
same issue here, is there any solutions ??

**Comment by johncongdon** [comment]
I have the same issue, except for the fact that it works in the emulator, or debug mode when my phone is connected to Android Studio.

Once I generate a Signed APK it breaks.

**Comment by cc2hh** [comment]
try it[#870](https://github.com/barteksc/AndroidPdfViewer/issues/870)

**Comment by LeoSnek** [comment]
As per the readme you need to add the line to `proguard-rules.pro`:

    -keep class com.shockwave.** { *; }
