### ISSUE TITLE
PDF File exists but PDFView says it doesnt crashes at random file missing.

### ISSUE THREAD

**Issue by 1stmetro** [barteksc/AndroidPdfViewer#86]
Hi, 

Been trying to resolve the issue of the PDF file existing every time but occasionally PDFView bombs out on a file.io exception with file not found, even with an if(file.exists) PDFView.fromfile etc it dies

if(file.exists()){pdfView.fromFile(file); }

It doesnt do it everytime but does it at random, the pdf is opened in a thread and destroyed when leaving the activity cant seem to resolve the issue so thought i would post here.

Kind regards,

09-04 11:08:31.244 31526-4959/com.appstrader.metro.the_engineer I/System.out: /storage/sdcard1/The Engineer Manuals/Advent/Comrec.pdf file.exists() = true

09-04 11:08:31.247 31526-4959/com.appstrader.metro.the_engineer E/AndroidRuntime: FATAL EXCEPTION: Thread-2207
Process: com.appstrader.metro.the_engineer, PID: 31526
java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.barteksc.pdfviewer.PDFView$Configurator com.github.barteksc.pdfviewer.PDFView.fromFile(java.io.File)' on a null object reference at com.appstrader.metro.the_engineer.ViewPDF$PlaceholderFragment$1$override.run(ViewPDF.java:384)
                                                                                      at com.appstrader.metro.the_engineer.ViewPDF$PlaceholderFragment$1$override.access$dispatch(ViewPDF.java)
                                                                                      at com.appstrader.metro.the_engineer.ViewPDF$PlaceholderFragment$1.run(ViewPDF.java:0)
                                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by 1stmetro** [comment]
Appears to of been a thread issue, when opening and closing the same activity with different pdf's, might be interesting for people to be aware of such issues.

**Comment by Lynishkm** [comment]
Please give a solution
