### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by vincecarterhu** [barteksc/AndroidPdfViewer#896]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference
        at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:756)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:80)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:27)
        at android.os.AsyncTask.finish(AsyncTask.java:692)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:709)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6517)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by Jeluchu** [comment]
Hello! I currently have exactly the same problem as you, I share my logcat although I think it is more or less the same as what you shared. In many occasions the PDF does not load me for this problem. I hope it can be fixed soon, although they have been a long time without maintaining this library

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.HandlerThread.isAlive()' on a null object reference
       at com.github.barteksc.pdfviewer.PDFView.a(PDFView.java:8)
       at com.github.barteksc.pdfviewer.DecodingAsyncTask.a(DecodingAsyncTask.java:22)
       at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:2)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

**Comment by 1stmetro** [comment]
Anyone want to post some code so we can see why you are getting the error, 

Although the library has not been updated for a while, i can confirm i have no issues with the code albeit i use my custom version but i have no issues.

**Comment by Jeluchu** [comment]
I am using the lower version than this because it works much better than the new one, since it seems that it is not supporting it

Also when I was testing the new version (`implementation 'com.github.barteksc:android-pdf-viewer:3.2.0-beta.1'`), the PDF load slowed down

If I see that it continues to fail and there is no maintenance, I will look for another library of this style

**Comment by EngDjango** [comment]
me too 
````
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.HandlerThread.isAlive()' on a null object reference
        at com.github.barteksc.pdfviewer.PDFView.loadComplete(PDFView.java:756)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:80)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.onPostExecute(DecodingAsyncTask.java:27)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
````

**Comment by 1stmetro** [comment]
You all have an error on a null reference obviously you are doing something wrong in your code by trying to reference to a null which then returns a null error, look at your code and see what is returning the null then replace the null with the correct reference.

**Comment by OzairGandhi** [comment]
PDFView quranMain;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_quran_main);
        try {
            quranMain = (PDFView) findViewById(R.id.QuranM);
            quranMain.fromAsset("MAITRIK.pdf").load();
        }catch (Exception e)
        {

same error
