### ISSUE TITLE
 load pdf error  java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by anjanaps** [barteksc/AndroidPdfViewer#961]
E/PDFView: load pdf error
 java.io.FileNotFoundException:
  at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:364)
        at android.content.res.AssetManager.open(AssetManager.java:338)
        at com.github.barteksc.pdfviewer.util.FileUtils.fileFromAsset(FileUtils.java:37)
        at com.github.barteksc.pdfviewer.source.AssetSource.createDocument(AssetSource.java:39)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
        at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by WisniewskiBlake** [comment]
Did you resolve this?

**Comment by smohanprasath** [comment]
me too have the same problem bro did you resolve it

**Comment by GovindSingh9447** [comment]
Hey, has anyone resolved this issue, I am also facing the same problem.

**Comment by shellzlhh** [comment]
If you are loading a PDF from a file in storage, please use the fromFile method instead of fromAsset.
