### ISSUE TITLE
report native crash

### ISSUE THREAD

**Issue by shizhangbiao** [barteksc/AndroidPdfViewer#98]
09-23 16:32:39.675 3251-13436 E/NativeCrashListener: Unable to report native crash
                                                       java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                           at java.util.ArrayList.get(ArrayList.java:308)
                                                           at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2566)
                                                           at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2156)

**Comment by shizhangbiao** [comment]
09-23 16:32:39.675 3251-13436 E/NativeCrashListener: Unable to report native crash
                                                       java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                           at java.util.ArrayList.get(ArrayList.java:308)
                                                           at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2566)
                                                           at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2156)
                                                           at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:10259)
                                                           at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:10152)
                                                           at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10802)
                                                           at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:10348)
                                                           at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

**Comment by shizhangbiao** [comment]
09-23 16:32:39.675 3251-13436 E/NativeCrashListener: Unable to report native crash
                                                       java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                           at java.util.ArrayList.get(ArrayList.java:308)
                                                           at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2566)
                                                           at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2156)
                                                           at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:10259)
                                                           at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:10152)
                                                           at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10802)
                                                           at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:10348)
                                                           at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

**Comment by abner27625** [comment]
ava.lang.ArithmeticException: divide by zero
                                                                            at com.github.barteksc.pdfviewer.PDFView.loadPageByOffset(PDFView.java:1009)
                                                                            at com.github.barteksc.pdfviewer.DragPinchManager.onScroll(DragPinchManager.java:136)
                                                                            at android.view.GestureDetector.onTouchEvent(GestureDetector.java:610)
                                                                            at com.github.barteksc.pdfviewer.DragPinchManager.onTouch(DragPinchManager.java:200)
                                                                            at android.view.View.dispatchTouchEvent(View.java:10008)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                            at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
                                                                            at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                            at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
                                                                            at android.view.View.dispatchPointerEvent(View.java:10232)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
                                                                            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6750)
                                                                            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6831)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:661)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
08-29 20:42:20.829 32336-32336/com.example.lenovo.pdf E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:761)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:156)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6531)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by JeffyLi1991** [comment]
Has this problem been resolved?

**Comment by durgeshchetu** [comment]
05-21 17:03:57.612 1531-6692/system_process E/NativeCrashListener: Unable to report native crash
    java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2598)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11505)
        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11402)
        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12086)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11597)
